package com.ujiuye.mis.pojo;

public class RoleSources {

    private Integer rsid;
    private String rsdis;
    private Integer resourcesFk;
    private Integer roleFk;

    public RoleSources(){};


    public RoleSources(Integer resourcesFk,Integer roleFk){
        this.resourcesFk=resourcesFk;
        this.roleFk=roleFk;
    }



    public Integer getRsid() {
        return rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.rsid
     *
     * @param rsid the value for role_sources.rsid
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public void setRsid(Integer rsid) {
        this.rsid = rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.rsdis
     *
     * @return the value of role_sources.rsdis
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public String getRsdis() {
        return rsdis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.rsdis
     *
     * @param rsdis the value for role_sources.rsdis
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public void setRsdis(String rsdis) {
        this.rsdis = rsdis == null ? null : rsdis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.resources_fk
     *
     * @return the value of role_sources.resources_fk
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public Integer getResourcesFk() {
        return resourcesFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.resources_fk
     *
     * @param resourcesFk the value for role_sources.resources_fk
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public void setResourcesFk(Integer resourcesFk) {
        this.resourcesFk = resourcesFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.role_fk
     *
     * @return the value of role_sources.role_fk
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public Integer getRoleFk() {
        return roleFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.role_fk
     *
     * @param roleFk the value for role_sources.role_fk
     *
     * @mbg.generated Tue Sep 22 15:00:02 CST 2020
     */
    public void setRoleFk(Integer roleFk) {
        this.roleFk = roleFk;
    }
}